name: Docker test, build, push

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'


jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check changes
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
      helm: ${{ steps.filter.outputs.helm }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout project to determine changed files
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: master
          filters: |
            docker:
              - '**.go'
              - 'testdata/**'
              - 'go.mod'
              - 'go.sum'
              - 'Dockerfile'
            helm:
              - '**.go'
              - 'testdata/**'
              - 'go.mod'
              - 'go.sum'
              - 'Dockerfile'
              - 'deploy/**'


  docker:
    needs: [changes]
    # run job if there were actual changes
    if: needs.changes.outputs.docker == 'true'
    with:
      event_name: ${{ github.event_name }}
    secrets: inherit
    uses: waldner/cert-manager-webhook-he/.github/workflows/docker.yaml@master

  helm:
    needs: [changes,docker]
    # run job if there were actual changes
    if: always() && ((needs.docker.result == 'skipped' && needs.changes.outputs.helm == 'true') || needs.docker.result == 'success')
    with:
      event_name: ${{ github.event_name }}
    secrets: inherit
    uses: waldner/cert-manager-webhook-he/.github/workflows/helm.yaml@master
